/* TESTING CONSTANTS, set to false on production */

const TEST_SEC_SINCE_START = false;

const TEST_EMPTY_CACHE_ON_START = false;
const TEST_FAIL_SILENT_SIGNIN = false;
const TEST_FAIL_LOAD_SERVER_DATA = false;
const TEST_FAIL_RENEW_SERVER_DATA = false;
const TEST_FAIL_SERVER_CONNECTABLE = false;
const TEST_FAST_NEG_TIMERS = false;

const ARE_TESTING = TEST_EMPTY_CACHE_ON_START
  || TEST_FAIL_SILENT_SIGNIN
  || TEST_FAIL_LOAD_SERVER_DATA
  || TEST_FAIL_SERVER_CONNECTABLE
  || TEST_SEC_SINCE_START || TEST_FAST_NEG_TIMERS;

if (ARE_TESTING) {
  if (TEST_EMPTY_CACHE_ON_START) console.log('TEST_EMPTY_CACHE_ON_START');
  if (TEST_FAIL_SILENT_SIGNIN) console.log('TEST_FAIL_SILENT_SIGNIN');
  if (TEST_FAIL_LOAD_SERVER_DATA) console.log('TEST_FAIL_LOAD_SERVER_DATA');
  if (TEST_FAIL_RENEW_SERVER_DATA) console.log('TEST_FAIL_RENEW_SERVER_DATA');
  if (TEST_FAIL_SERVER_CONNECTABLE) console.log('TEST_FAIL_SERVER_CONNECTABLE');
  if (TEST_SEC_SINCE_START) console.log('TEST_SEC_SINCE_START');
  if (TEST_FAST_NEG_TIMERS) console.log('TEST_FAST_NEG_TIMERS');
}


export {
  TEST_EMPTY_CACHE_ON_START,
  TEST_FAIL_SILENT_SIGNIN,
  TEST_FAIL_LOAD_SERVER_DATA,
  TEST_FAIL_RENEW_SERVER_DATA,
  TEST_FAIL_SERVER_CONNECTABLE,
  TEST_SEC_SINCE_START,
  TEST_FAST_NEG_TIMERS
};
